name: Deploy to Hazel Droplet

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, xml, gd, pdo_sqlite

      - name: Install Composer
        run: |
          composer --version || (
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          )

      - name: Start SSH Agent and Add Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: 22
          script: |
            set -e
            cd ${{ secrets.DROPLET_PATH }}
            echo " Updating repository..."
            git fetch --all
            git reset --hard origin/main
            git clean -fd
            echo " Installing dependencies..."
            composer install --no-interaction --prefer-dist --optimize-autoloader
            npm ci
            npm run build
            echo " Clearing old caches..."
            php artisan optimize:clear || true
            
            echo " Rebuilding optimized caches..."
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # echo " Fixing permissions..."
            # chown -R forge:forge ${{ secrets.DROPLET_PATH }}
            # chmod -R 775 ${{ secrets.DROPLET_PATH }}/storage ${{ secrets.DROPLET_PATH }}/bootstrap/cache || true
            echo " Fixing permissions..."
            chown -R forge:forge storage bootstrap/cache
            chmod -R 775 storage bootstrap/cache || true

            echo " Restarting services..."
            systemctl restart php8.3-fpm || true
            systemctl reload nginx || true
            echo " Deployment complete!"
